//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlarnaWebAPI
{
    using KlarnaWebAPI.Config;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.EntityClient;
    
    public partial class Lafiesta50Entities : DbContext
    {
        public Lafiesta50Entities()
            : base("name=Lafiesta50Entities")
        {
        }

        public Lafiesta50Entities(string sConnectionString)
            : base(sConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Klarna_Order> Klarna_Orders { get; set; }

        public static Lafiesta50Entities Create(string providerConnectionString)
        {
            var entityBuilder = new EntityConnectionStringBuilder();

            // use your ADO.NET connection string
            entityBuilder.ProviderConnectionString = providerConnectionString;
            entityBuilder.Provider = "System.Data.SqlClient";
            // Set the Metadata location.
            //entityBuilder.Metadata = @"res://*/Database.DWH.DWModel.csdl|res://*/Database.DWH.DWModel.ssdl|res://*/Database.DWH.DWModel.msl";
            entityBuilder.Metadata = @"res://*/KlarnaModel.csdl|res://*/KlarnaModel.ssdl|res://*/KlarnaModel.msl";

            return new Lafiesta50Entities(entityBuilder.ConnectionString);
        }

        public String BuildConnectionString()
        {

            String DataSource = "";
            String Database = "";

            Props config = new Props("Config.txt");
            DataSource = config.get("datasource", "");
            Database = config.get("initialcatalog", "");

            // Build the connection string from the provided datasource and database
            String connString = @"data source=" + DataSource +
            ";initial catalog=" + Database +
            ";integrated security=True;MultipleActiveResultSets=True;App=EntityFramework;";

            // Build the MetaData... feel free to copy/paste it from the connection string in the config file.
            EntityConnectionStringBuilder esb = new EntityConnectionStringBuilder();
            esb.Metadata = "res://*/AW_Model.csdl|res://*/AW_Model.ssdl|res://*/AW_Model.msl";
            esb.Provider = "System.Data.SqlClient";
            esb.ProviderConnectionString = connString;

            // Generate the full string and return it
            return esb.ToString();
        }

    }
}
