//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlarnaWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klarna_Order
    {
        public byte[] timestamp { get; set; }
        public string CompName { get; set; }
        public string OrderNo_ { get; set; }
        public string KlarnaID { get; set; }
        public string Internal_Order_Id { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Time_Created { get; set; }
        public int OrderType { get; set; }
        public decimal Amount { get; set; }
        public decimal Vat_Amount { get; set; }
        public int Status_Payment { get; set; }
        public string Status_Payment_Text { get; set; }
    }
}
